import { NextResponse } from "next/server";
import { readFileSync } from "node:fs";
import { join } from "node:path";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/**
 * The Hall of Fame, served from the ledger.
 *
 * The 89 audited kernels are the project's actual asset, and until now they
 * were reachable only by reading JSON files in the repo — the dashboard showed
 * run history and interactive labs, but never the results themselves. This
 * route exposes them, and deliberately ships the caveats alongside the wins:
 * measured-vs-modelled speedup, provenance (was this discovered or is it the
 * seeded law?), and whether the kernel is safe outside its training band.
 *
 * No database involved: ledger/*.json is the source of truth.
 */

interface Measured {
  measuredSpeedup?: number;
  resolvable?: boolean;
}

interface LedgerEntry {
  taskId: string;
  title?: string;
  metric: number;
  level: number;
  formula: string;
  holdout?: number;
  speed?: {
    formulaCost?: number;
    exactCost?: number;
    speedup?: number;
    speedupModelled?: number;
    speedupSource?: string;
    measured?: Measured;
    vsIterative?: { label: string; speedup: number };
  };
  fast?: {
    formula: string;
    metric: number;
    formulaCost?: number;
    measured?: Measured;
  };
}

interface AuditRow {
  id: string;
  provenance?: string;
  r2?: number | null;
  issues?: { code: string; severity: string; detail: string }[];
}

let cache: { at: number; payload: unknown } | null = null;
const TTL_MS = 30_000;

export async function GET() {
  if (cache && Date.now() - cache.at < TTL_MS) {
    return NextResponse.json(cache.payload);
  }

  const root = process.cwd();
  const ledger = JSON.parse(readFileSync(join(root, "spear-hall-of-fame.json"), "utf8")) as Record<string, LedgerEntry>;

  // The audit report carries provenance and the risk flags. It is generated by
  // `npx tsx scripts/audit-champions.ts --json`; if it is missing or stale we
  // still serve the ledger rather than failing, but we say so.
  let audit: Record<string, AuditRow> = {};
  let auditAvailable = false;
  try {
    const raw = JSON.parse(readFileSync(join(root, "REPORTS", "champion-audit.json"), "utf8")) as { rows: AuditRow[] };
    audit = Object.fromEntries(raw.rows.map((r) => [r.id, r]));
    auditAvailable = true;
  } catch {
    auditAvailable = false;
  }

  const RISK = new Set(["ood-violation", "low-r2"]);

  const kernels = Object.values(ledger).map((e) => {
    const a = audit[e.taskId];
    const codes = new Set((a?.issues ?? []).map((i) => i.code));
    const measured = e.speed?.measured;
    const fastMeasured = e.fast?.measured;
    return {
      id: e.taskId,
      title: e.title ?? e.taskId,
      formula: e.formula,
      mse: e.metric,
      level: e.level,
      holdout: e.holdout ?? null,
      exact: e.metric < 1e-25,
      // speed: measured wins over modelled wherever a real measurement exists
      speedup: e.speed?.speedup ?? null,
      speedupModelled: e.speed?.speedupModelled ?? null,
      speedupMeasured: measured?.resolvable ? (measured.measuredSpeedup ?? null) : null,
      speedUnresolvable: measured ? measured.resolvable === false : null,
      vsIterative: e.speed?.vsIterative ?? null,
      cost: e.speed?.formulaCost ?? null,
      fast: e.fast
        ? {
            formula: e.fast.formula,
            mse: e.fast.metric,
            cost: e.fast.formulaCost ?? null,
            speedupMeasured: fastMeasured?.resolvable ? (fastMeasured.measuredSpeedup ?? null) : null,
          }
        : null,
      provenance: a?.provenance ?? null,
      r2: a?.r2 ?? null,
      risky: [...codes].filter((c) => RISK.has(c)),
    };
  });

  const payload = {
    generatedAt: new Date().toISOString(),
    auditAvailable,
    total: kernels.length,
    summary: {
      exact: kernels.filter((k) => k.exact).length,
      safe: kernels.filter((k) => k.risky.length === 0).length,
      withFastSlot: kernels.filter((k) => k.fast).length,
      fastSlotsWorthIt: kernels.filter((k) => (k.fast?.speedupMeasured ?? 0) >= 1.2).length,
      searchFound: kernels.filter((k) => k.provenance === "search").length,
      rewriteOfLaw: kernels.filter((k) => k.provenance === "rewrite-of-law").length,
      recoveredSeed: kernels.filter((k) => k.provenance === "recovered-seed").length,
    },
    kernels,
  };

  cache = { at: Date.now(), payload };
  return NextResponse.json(payload);
}
